#!/bin/bash

set -euxo pipefail

# build platform-specific Docker images
docker build -f Dockerfile.amd64 -t putty182/spotify-ripper:latest-amd64 .
docker build -f Dockerfile.arm32v7 -t putty182/spotify-ripper:latest-arm32v7 .

